"""empty message

Revision ID: 142d9fc85699
Revises: b1b6721c93af
Create Date: 2021-03-11 08:06:48.436028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142d9fc85699'
down_revision = 'b1b6721c93af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'checked')
    # ### end Alembic commands ###
