"""empty message

Revision ID: 2d59a677eca0
Revises: ed0e8d4f003c
Create Date: 2021-03-04 19:20:00.945565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d59a677eca0'
down_revision = 'ed0e8d4f003c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('achieved_challenges', sa.Integer(), nullable=True))
    op.drop_column('user', 'achieved_challenge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('achieved_challenge', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'achieved_challenges')
    # ### end Alembic commands ###
