"""empty message

Revision ID: 5321c08ff3b0
Revises: f4397d2e81c3
Create Date: 2021-03-02 18:25:02.706447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5321c08ff3b0'
down_revision = 'f4397d2e81c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('challenges_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('achieved_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('challenge', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='challenges_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='challenges_pkey'),
    sa.UniqueConstraint('id', name='challenges_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users_challenges',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name='users_challenges_challenge_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='users_challenges_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'challenge_id', name='users_challenges_pkey')
    )
    op.drop_table('notifications')
    # ### end Alembic commands ###
