"""empty message

Revision ID: 762ce1e80908
Revises: 909278ac8820
Create Date: 2021-03-10 22:02:23.232399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762ce1e80908'
down_revision = '909278ac8820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_challenge', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'last_challenge')
    # ### end Alembic commands ###
