"""empty message

Revision ID: 909278ac8820
Revises: eeab553d14dc
Create Date: 2021-03-07 18:22:24.479124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909278ac8820'
down_revision = 'eeab553d14dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'challenges', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenges', type_='unique')
    # ### end Alembic commands ###
