"""empty message

Revision ID: 98102f7112ce
Revises: cafeb7918f00
Create Date: 2021-03-02 18:05:14.604307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98102f7112ce'
down_revision = 'cafeb7918f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_challenges')
    op.drop_table('challenges')
    op.drop_table('notifications')
    op.drop_column('user', 'daily_challenge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('daily_challenge', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_table('challenges',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('challenges_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('achieved_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('challenge', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='challenges_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='challenges_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users_challenges',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name='users_challenges_challenge_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='users_challenges_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'challenge_id', name='users_challenges_pkey')
    )
    # ### end Alembic commands ###
