"""empty message

Revision ID: b1b6721c93af
Revises: 762ce1e80908
Create Date: 2021-03-10 22:16:42.251551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b6721c93af'
down_revision = '762ce1e80908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('today_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'today_completed')
    # ### end Alembic commands ###
