"""empty message

Revision ID: fe513e60b026
Revises: 31847d4e279a
Create Date: 2021-03-02 18:35:52.961245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe513e60b026'
down_revision = '31847d4e279a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('daily_challenge', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'daily_challenge')
    # ### end Alembic commands ###
